/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Carousels: typeof import('./components/common/Carousels.vue')['default']
    ConfirmDialog: typeof import('./components/dialog/ConfirmDialog.vue')['default']
    DataTable: typeof import('./components/common/DataTable.vue')['default']
    Loading: typeof import('./components/common/Loading.vue')['default']
    LogoutDialog: typeof import('./components/dialog/LogoutDialog.vue')['default']
    MsgDialog: typeof import('./components/dialog/MsgDialog.vue')['default']
    Pagination: typeof import('./components/common/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
