/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/buyer/Cart': RouteRecordInfo<'/buyer/Cart', '/buyer/Cart', Record<never, never>, Record<never, never>>,
    '/buyer/Checkout': RouteRecordInfo<'/buyer/Checkout', '/buyer/Checkout', Record<never, never>, Record<never, never>>,
    '/buyer/Order': RouteRecordInfo<'/buyer/Order', '/buyer/Order', Record<never, never>, Record<never, never>>,
    '/buyer/Product': RouteRecordInfo<'/buyer/Product', '/buyer/Product', Record<never, never>, Record<never, never>>,
    '/default/Login': RouteRecordInfo<'/default/Login', '/default/Login', Record<never, never>, Record<never, never>>,
    '/default/Signup': RouteRecordInfo<'/default/Signup', '/default/Signup', Record<never, never>, Record<never, never>>,
    '/seller/Analysis': RouteRecordInfo<'/seller/Analysis', '/seller/Analysis', Record<never, never>, Record<never, never>>,
    '/seller/OrderDetail': RouteRecordInfo<'/seller/OrderDetail', '/seller/OrderDetail', Record<never, never>, Record<never, never>>,
    '/seller/OrderManage': RouteRecordInfo<'/seller/OrderManage', '/seller/OrderManage', Record<never, never>, Record<never, never>>,
    '/seller/ProductManage': RouteRecordInfo<'/seller/ProductManage', '/seller/ProductManage', Record<never, never>, Record<never, never>>,
    '/seller/ProductMange/AddProduct': RouteRecordInfo<'/seller/ProductMange/AddProduct', '/seller/ProductMange/AddProduct', Record<never, never>, Record<never, never>>,
    '/seller/ProductMange/ModifyProduct': RouteRecordInfo<'/seller/ProductMange/ModifyProduct', '/seller/ProductMange/ModifyProduct', Record<never, never>, Record<never, never>>,
    '/seller/ProductMange/ProductList': RouteRecordInfo<'/seller/ProductMange/ProductList', '/seller/ProductMange/ProductList', Record<never, never>, Record<never, never>>,
    '/seller/ProductMange/Upload': RouteRecordInfo<'/seller/ProductMange/Upload', '/seller/ProductMange/Upload', Record<never, never>, Record<never, never>>,
  }
}
