/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/buyer/Cart': RouteRecordInfo<'/buyer/Cart', '/buyer/Cart', Record<never, never>, Record<never, never>>,
    '/buyer/Checkout': RouteRecordInfo<'/buyer/Checkout', '/buyer/Checkout', Record<never, never>, Record<never, never>>,
    '/buyer/Order': RouteRecordInfo<'/buyer/Order', '/buyer/Order', Record<never, never>, Record<never, never>>,
    '/buyer/Product': RouteRecordInfo<'/buyer/Product', '/buyer/Product', Record<never, never>, Record<never, never>>,
    '/home/Home': RouteRecordInfo<'/home/Home', '/home/Home', Record<never, never>, Record<never, never>>,
    '/login/Login': RouteRecordInfo<'/login/Login', '/login/Login', Record<never, never>, Record<never, never>>,
    '/sell/AddProduct': RouteRecordInfo<'/sell/AddProduct', '/sell/AddProduct', Record<never, never>, Record<never, never>>,
    '/sell/dashboard/Dashboard': RouteRecordInfo<'/sell/dashboard/Dashboard', '/sell/dashboard/Dashboard', Record<never, never>, Record<never, never>>,
    '/sell/Product': RouteRecordInfo<'/sell/Product', '/sell/Product', Record<never, never>, Record<never, never>>,
  }
}
